// Properties/Settings.Designer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód vytvořil nástroj.
//     Runtime Version:4.0.30319.42000
//
//     Změny v tomto souboru mohou způsobit nesprávné chování a budou ztraceny, pokud
//     kód znovu vygeneruješ.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivesViewer.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoRedraw
        {
            get
            {
                return ((bool)(this["AutoRedraw"]));
            }
            set
            {
                this["AutoRedraw"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color ColorSpeed
        {
            get
            {
                return ((global::System.Drawing.Color)(this["ColorSpeed"]));
            }
            set
            {
                this["ColorSpeed"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ColorBrake
        {
            get
            {
                return ((global::System.Drawing.Color)(this["ColorBrake"]));
            }
            set
            {
                this["ColorBrake"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color ColorLeftCurve
        {
            get
            {
                return ((global::System.Drawing.Color)(this["ColorLeftCurve"]));
            }
            set
            {
                this["ColorLeftCurve"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color ColorRightCurve
        {
            get
            {
                return ((global::System.Drawing.Color)(this["ColorRightCurve"]));
            }
            set
            {
                this["ColorRightCurve"] = value;
            }
        }
    }
}
